### ISSUE TITLE
スマホを繋いでスマホでゲームの操作を試すやり方を知る

### ISSUE THREAD

**Issue by JiaChen-Zeng** [Geijo-Games/GG02#20]
スマホのゲームなので、操作を実験・改善するにはまずゲームをスマホで開けないと。

たぶん速いと思う。全員がやり方わかるように、簡単にやり方をここに記載しておいてください。直接参考リンク貼っても大丈夫。

**Comment by Monobesatoshi** [comment]
ビルド前のエラーを解消すべき。おそらくアセットが影響している

**Comment by JiaChen-Zeng** [comment]
WebGL でもビルドできない。リアクターにエラーがある。

```
BlendTree "Blend Tree" in state "Blend Tree" in Controller "RightLidJoint " uses parameter "Blend" which does not exist.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error building Player: BlendTree "Blend Tree" in state "Blend Tree" in Controller "RightLidJoint " uses parameter "Blend" which does not exist.

BlendTree "Blend Tree" in state "Blend Tree" in Controller "RightLidJoint " uses parameter "Blend" which does not exist.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Build completed with a result of 'Failed' in 12 seconds (11766 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by Monobesatoshi** [comment]
Androidでのビルド（非推奨）
building settingsからAndroidを選んでswitch platformを押す
buildを押す
おそらくうまく行かないので
android-ndk-r19
gradle-7.3.2
jdk-17.0.1
をダウンロードする
unity のEdit->Prefarence->External Toolsからダウンロードしたものを選択する
ビルドすると失敗する

**Comment by JiaChen-Zeng** [comment]
ぼくのほうで Android のビルドをやってみます。

**Comment by JiaChen-Zeng** [comment]
Build Settings で Android に切り替える。その前に Unity Hub で Android 関連のものをインストールする必要がある。インストールが完成しても切り替えられなかったので、Unity を再起動してみるとできた。Build And Run すると JDK の設定がされていないとエラーが出て進められない。なので再度 Unity Hub に戻って OpenJDK をインストールし、Unity を再起動してみる。今回はスマホを差し込んでみた。実行すると

![image](https://user-images.githubusercontent.com/3676278/147477451-de15d5f9-30a3-4837-a0c9-61b4c5b5f9c5.png)

スマホを検出できなかったようだ。[Unity Manual](https://docs.unity3d.com/Manual/android-sdksetup.html) を見てみると、USB Debugging がオフになってたのが原因かもしれない。オンにして再度トライ。今度はできた。

https://imgur.com/a/dQDN3D1

上の Unity Manual の通りですね。1 と 2 番をやれば Android で実行できる。

**Comment by JiaChen-Zeng** [comment]
一応ぼくはできたので完成とします
