### ISSUE TITLE
`reactor` と子オブジェの壁面を物理上繋がるようにする

### ISSUE THREAD

**Issue by JiaChen-Zeng** [Geijo-Games/GG02#27]
今物理上繋がっていないので、`reactor` をまとまった個体として制御できない。解決するには `Fixed Joint 2D` を使う。

参照： #24

**Comment by JiaChen-Zeng** [comment]
`reactor`：`Rigidbody 2D` を追加。その `Body Type` を `Kinematic` に設定。
`reactor_frame`、`reactor_top_lid`、`reactor_left_lid_red`、`reactor_right_lid_red`、`reactor_bottom_lid`：`Fixed Joint 2D` を追加。その `Connected Rigid Body` を `reactor` に設定。

これで物理上繋がるが、蓋のアニメーションはおかしくなってしまう。蓋が回転しなくなるのがいけない。もうこれは蓋開閉をやってる @SuperSharkman に任せた。

**Comment by JiaChen-Zeng** [comment]
@SuperSharkman のアドバイスを受けて壁面のオブジェクトの `Body Type` を `Kinematic` に変更。しかし、そうすると摩擦力が完全に効かなくなる。なのでこの案はダメ。

https://imgur.com/a/sytKnof

**Comment by JiaChen-Zeng** [comment]
一見摩擦力が効くようになったが、少し時間が経ったら宝石の挙動がおかしくなる。宝石が特定の蓋に近づくと間違った方向へと摩擦力が加えられるように見えた。また、実行中に蓋のオブジェクトをすべて確認したが、蓋が閉じているか開いているかに関わらず `Body Type` が `Kinematic` になっている。

もう一度修正をお願いします。

https://imgur.com/a/2Q8f6Di

**Comment by SuperSharkman** [comment]
蓋の摩擦力が効かないことはタイマーの問題なので、修正した。また右の蓋の`Animator controller`も修正した。テストを行って、正常に動くようになると思います。

**Comment by JiaChen-Zeng** [comment]
確認しました。問題なさそうですね。これは完成です。
